base:
  project: dvc_project
  random_state: 42
  target_col: quality
  test_size: 0.2

data_source:
  data_file: data/wine_quality.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/data.csv

  split_data:
    processed_data_dir: artifacts/processed_data
    train_path: artifacts/processed_data/train.csv
    test_path: artifacts/processed_data/test.csv

  reports:
    reports_dir: artifacts/report
    params: artifacts/report/params.json
    scores: artifacts/report/scores.json
  
  model_dir: artifacts/saved_models
  

estimators:
  ElasticNet:
    params: 
      alpha: 0.9
      l1_ratio: 0.4